Update to rustix 1.1.5 that fixes some build errors
We're getting:
```
error: attributes starting with `rustc` are reserved for use by the `rustc` compiler
  --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustix-0.36.5/src/backend/linux_raw/io/errno.rs:28:25
   |
28 | #[cfg_attr(rustc_attrs, rustc_layout_scalar_valid_range_start(0xf001))]
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

due to https://github.com/bytecodealliance/rustix/issues/1620.

So, update to rustix 1.1.5 which fixes this.

Signed-off-by: Alexander Larsson <alexl@redhat.com>